language: java

dist: trusty

jdk:
  - oraclejdk8

sudo: false

before_install:
  - wget http://services.gradle.org/distributions/gradle-5.0-bin.zip
  - unzip -qq gradle-5.0-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.0
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

install: true

script: gradle build -x signArchives

notifications:
  email: false
