language: java

dist: trusty

jdk:
  - openjdk11

sudo: false

before_install:
  - wget http://services.gradle.org/distributions/gradle-6.1-bin.zip
  - unzip -qq gradle-6.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

install: true

script: gradle build -x signArchives

notifications:
  email: false
